# Generated by Django 4.2.1 on 2023-05-18 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0002_card_belongs"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="date_next",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
