# Generated by Django 4.2.1 on 2023-05-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0002_remove_card_card_type_user_new_cards_added_today"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="interval",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="new_cards_added_today",
            field=models.IntegerField(default=0),
        ),
    ]
