# Generated by Django 4.2.1 on 2023-05-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0003_alter_card_interval_alter_user_new_cards_added_today"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="time_next_today",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
