# Generated by Django 4.2.1 on 2023-05-24 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0004_card_time_next_today"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dtime_now", models.DateTimeField()),
                ("quality", models.IntegerField()),
                ("interval_before", models.IntegerField()),
                ("interval_after", models.IntegerField()),
                ("easiness_before", models.FloatField()),
                ("easiness_after", models.FloatField()),
                ("date_scheduled_before", models.DateField()),
                ("date_scheduled_after", models.DateField()),
                (
                    "belongs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="survey.card"
                    ),
                ),
            ],
        ),
    ]
