# Generated by Django 4.2.1 on 2023-05-24 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0007_user_last_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_used",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
