# Generated by Django 4.2.1 on 2023-05-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0011_rename_program_assessment_subject_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="time_for_initial_assessment",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
