# Generated by Django 4.2.1 on 2023-05-26 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0012_alter_user_time_for_initial_assessment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_final_opens",
            field=models.DateField(default=datetime.date(2023, 5, 26)),
            preserve_default=False,
        ),
    ]
