# Generated by Django 4.2.1 on 2023-05-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0016_remove_user_time_for_final_assessment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentsubmission",
            name="time_taken",
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
