# Generated by Django 4.2.1 on 2023-06-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0022_user_experiment_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="back",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="card",
            name="front",
            field=models.TextField(),
        ),
    ]
