# Generated by Django 4.2.1 on 2023-06-01 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0023_alter_card_back_alter_card_front"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="date_next",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_used",
            field=models.DateField(default=django.utils.timezone.localtime),
        ),
    ]
