# Generated by Django 4.2.1 on 2023-06-03 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0024_alter_card_date_next_alter_user_last_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="created",
            field=models.DateField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 6, 2, 20, 35, 0, 489020, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
