# Generated by Django 4.2.1 on 2023-06-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0025_card_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="initialsurvey",
            name="study_outside",
            field=models.CharField(
                choices=[
                    ("nothing", "No studying outside school"),
                    ("minimal", "Studying for less than 30 minutes outside of school"),
                    (
                        "medium",
                        "Studying for more than 30 minutes but less than an hour outside of school",
                    ),
                    ("large", "Studying for more than an hour outside of school"),
                ],
                default="nothing",
                max_length=100,
            ),
        ),
    ]
