# Generated by Django 4.2.1 on 2023-06-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0027_alter_user_experiment_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="initialsurvey",
            name="flashcard_skill",
        ),
        migrations.RemoveField(
            model_name="initialsurvey",
            name="use_flashcards_normally",
        ),
        migrations.AddField(
            model_name="initialsurvey",
            name="how_many_times_used_flashcards",
            field=models.CharField(
                choices=[
                    ("0", "0"),
                    ("1-2", "1-2"),
                    ("3-5", "3-5"),
                    ("5-10", "5-10"),
                    ("more than 10", "more than 10"),
                ],
                default="3-5",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="initialsurvey",
            name="study_outside",
            field=models.CharField(
                choices=[
                    (
                        "<30m",
                        "Studying for less than 30 minutes outside of school every week",
                    ),
                    ("1-2h", "Studying for 1-2 hours outside of school every week"),
                    ("3-4", "Studying for 3-4 hours outside of school every week"),
                    (
                        "5",
                        "Studying for more than 5 hours outside of school every week",
                    ),
                ],
                default="<30m",
                max_length=100,
            ),
        ),
    ]
