# Generated by Django 4.2.1 on 2023-06-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0028_remove_initialsurvey_flashcard_skill_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assessment",
            old_name="correct_answers",
            new_name="correct_answers_start",
        ),
        migrations.RenameField(
            model_name="assessment",
            old_name="questions",
            new_name="questions_start",
        ),
        migrations.AddField(
            model_name="assessment",
            name="correct_answers_end",
            field=models.TextField(default="[1,2,3]"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assessment",
            name="questions_end",
            field=models.TextField(default="TODO"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="surveygroup",
            name="cards_per_week",
            field=models.PositiveIntegerField(default=45),
        ),
        migrations.AddField(
            model_name="surveygroup",
            name="topics_to_make",
            field=models.TextField(
                default='[["astro", "thing"], ["arst", "brst"], ["crst", "drst"], ["irst", "pirst"], ["gov", "gov2", "gov3"]]'
            ),
            preserve_default=False,
        ),
    ]
