# Generated by Django 4.2.1 on 2023-06-19 16:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "survey",
            "0029_rename_correct_answers_assessment_correct_answers_start_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="initialsurvey",
            name="used_flashcards",
        ),
    ]
