# Generated by Django 4.2.1 on 2023-06-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0030_remove_initialsurvey_used_flashcards"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveygroup",
            name="ai_cards",
            field=models.TextField(
                default=[
                    {"answer": "Test is this", "question": "What is test?"},
                    {"answer": "You are this", "question": "Who are you?"},
                ]
            ),
            preserve_default=False,
        ),
    ]
