# Generated by Django 4.2.1 on 2023-07-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0031_surveygroup_ai_cards"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="suspended",
            field=models.BooleanField(default=False),
        ),
    ]
