# Generated by Django 4.2.2 on 2023-07-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0032_card_suspended"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveygroup",
            name="ai_naive_cards",
            field=models.TextField(
                default='["TODO FIX ME BY RUNNING for sg in SurveyGroup.objects.all(): sg.ai_naive_cards = sg.ai_cards; sg.save"]'
            ),
            preserve_default=False,
        ),
    ]
